# Generated by Django 3.2 on 2021-04-24 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cate', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id_ejem', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('stock_disponible', models.IntegerField()),
                ('stock_ocupado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ejemplar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=250)),
                ('editorial', models.CharField(max_length=250)),
                ('fecha_publicacion', models.DateField()),
                ('edicion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('numero_pres', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField()),
            ],
            options={
                'db_table': 'prestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('numero_res', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('numero_solicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('hora_solicitud', models.DateField()),
            ],
            options={
                'db_table': 'solicitud_prestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_doc', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id_tipo', models.BooleanField()),
                ('tipo', models.CharField(max_length=35)),
                ('tipo_prestamo_id', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipo_prestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut_usr', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_p', models.CharField(max_length=30)),
                ('apellido_m', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=150)),
                ('foto', models.CharField(blank=True, max_length=1, null=True)),
                ('huella', models.CharField(blank=True, max_length=1, null=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitudPrestamo',
            fields=[
                ('fecha_devolucion', models.DateField()),
                ('hora_devolucion', models.DateField()),
                ('fecha_devolucion_real', models.DateField()),
                ('hora_devolucion_real', models.DateField()),
                ('id_ejemplar', models.OneToOneField(db_column='id_ejemplar', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BiblioBec.ejemplar')),
            ],
            options={
                'db_table': 'detalle_solicitud_prestamo',
                'managed': False,
            },
        ),
    ]
