# Generated by Django 3.2 on 2021-04-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioBec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMedio',
            fields=[
                ('id_medio', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipo_medio',
                'managed': False,
            },
        ),
    ]
